### ISSUE TITLE
Bug: component gets hidden

### ISSUE THREAD

**Issue by tech-bash** [anurag629/IET_AGRA#2]
On refreshing the dashboard page addCourses component gets lost and is not displayed ..

SS:
![image](https://github.com/anurag629/IET_AGRA/assets/76992919/85280814-f7f0-4701-98f3-69f0d9b378c6)

**Comment by anurag629** [comment]
@tech-bash I don't think this is a bug. Components require a `user_type`, and when the backend doesn't load, it doesn't display the 'Add Course' option.

we deployed the backend on Render, it automatically shuts down when not in use.

**Comment by tech-bash** [comment]
Ok, but when we try to get the information after the backend is not used then it was not displaying it, even on multiple refresh. So you have to restart the backend server each time it gets shut down? One has to logout and login again and again to make the backend active ig, so not a frontend issue rather a backend one!

**Comment by anurag629** [comment]
> Ok, but when we try to get the information after the backend is not used then it was not displaying it, even on multiple refresh. So you have to restart the backend server each time it gets shut down? One has to logout and login again and again to make the backend active ig, so not a frontend issue rather a backend one!

We can somewhat say yes, but it's not a frontend or backend issue; rather, it's due to deployment.

**Comment by tech-bash** [comment]
Right
